### ISSUE TITLE
zellij overrides the keybinds when same are used in nvim

### ISSUE THREAD

**Issue by stankovictab** [Lilja/zellij.nvim#5]
I've bound Ctrl + h/j/k/l to ZellijNavigate... in nvim and the same bind for moving through panes in zellij, 
however the zellij keybind overrides the nvim one and I can't move between windows inside of nvim anymore. 
This probably has something to do with zellij recognizing the current pane is running nvim and therefore needs to somehow unhook those keybinds, to allow for nvim to use it's own. 
I'm sure this is a common problem, however I couldn't find a solution. 
Any help? :)

**Comment by stankovictab** [comment]
Slight correction, I see now that Ctrl + j can't be bound in zellij, but still the same issue applies for Alt + h/j/k/l too.

**Comment by Lilja** [comment]
Hey @stankovictab thanks for trying my plugin.

I think zellij at this point is a bit bleeding edge still with features missing. I switched back to tmux. This plugin won't really work without some features described in #3. See [my comment](https://github.com/Lilja/zellij.nvim/issues/3#issuecomment-1708088629).

I don't think this plugin will work without it. But the issue has been opened for a long time and nothing seems to be worked on.

**Comment by stankovictab** [comment]
Yeah, that's what I was worried about.. 
Well for now I'll stick to different sets of keybindings for moving through them both.. Thanks! :)
